const QUOTES = [
  { text: "The body achieves what the mind believes.", author: "Unknown" },
  { text: "Take care of your body. It's the only place you have to live.", author: "Jim Rohn" },
  { text: "Health is not about the weight you lose, but the life you gain.", author: "Unknown" },
  { text: "Your health is an investment, not an expense.", author: "Unknown" },
  { text: "Don't wish for a good body. Work for it.", author: "Unknown" },
  { text: "The groundwork for all happiness is good health.", author: "Leigh Hunt" },
  { text: "It never gets easier. You just get stronger.", author: "Unknown" },
  { text: "Strive for progress, not perfection.", author: "Unknown" },
  { text: "You are what you eat. So don't be fast, cheap, easy, or fake.", author: "Unknown" },
  { text: "Small steps every day lead to big changes over time.", author: "Unknown" },
  { text: "Your body is your most priceless possession. Take care of it.", author: "Jack Lalanne" },
  { text: "Motivation is what gets you started. Habit is what keeps you going.", author: "Jim Ryun" },
  { text: "A healthy outside starts from the inside.", author: "Robert Urich" },
  { text: "The secret of getting ahead is getting started.", author: "Mark Twain" },
  { text: "Nothing will work unless you do.", author: "Maya Angelou" },
  { text: "Success is the sum of small efforts repeated day in and day out.", author: "Robert Collier" },
  { text: "You don't have to be great to start, but you have to start to be great.", author: "Zig Ziglar" },
  { text: "Believe in yourself and all that you are.", author: "Christian D. Larson" },
  { text: "Discipline is the bridge between goals and accomplishment.", author: "Jim Rohn" },
  { text: "The only bad workout is the one that didn't happen.", author: "Unknown" },
  { text: "Every day is a new beginning. Take a deep breath and start again.", author: "Unknown" },
  { text: "Your future self is watching you right now through your memories.", author: "Aubrey De Grey" },
  { text: "Strength does not come from physical capacity. It comes from an indomitable will.", author: "Gandhi" },
  { text: "Wake up with determination. Go to bed with satisfaction.", author: "Unknown" },
  { text: "You are stronger than you think.", author: "Unknown" },
  { text: "One healthy choice leads to another.", author: "Unknown" },
  { text: "Don't stop when you're tired. Stop when you're done.", author: "Unknown" },
  { text: "The pain you feel today will be the strength you feel tomorrow.", author: "Unknown" },
  { text: "Eat well. Move more. Stress less. Sleep better.", author: "Unknown" },
  { text: "A year from now you'll wish you had started today.", author: "Karen Lamb" },
  { text: "The difference between try and triumph is a little umph.", author: "Marvin Phillips" },
  { text: "Energy and persistence conquer all things.", author: "Benjamin Franklin" },
  { text: "You don't find the will to win. You bring it with you.", author: "Unknown" },
  { text: "Commit to be fit.", author: "Unknown" },
  { text: "Be stronger than your excuses.", author: "Unknown" },
  { text: "Sweat is just fat crying.", author: "Unknown" },
  { text: "Your only limit is you.", author: "Unknown" },
  { text: "Push yourself because no one else is going to do it for you.", author: "Unknown" },
  { text: "Great things never came from comfort zones.", author: "Unknown" },
  { text: "Dream it. Wish it. Do it.", author: "Unknown" },
  { text: "The harder you work for something, the greater you'll feel when you achieve it.", author: "Unknown" },
  { text: "Don't limit your challenges. Challenge your limits.", author: "Unknown" },
  { text: "The best project you'll ever work on is you.", author: "Unknown" },
  { text: "Eat food. Not too much. Mostly plants.", author: "Michael Pollan" },
  { text: "Champions aren't made in the gyms. Champions are made from something deep inside.", author: "Muhammad Ali" },
  { text: "It's not about perfect. It's about effort.", author: "Jillian Michaels" },
  { text: "The secret is to make the workouts interesting.", author: "Unknown" },
  { text: "You don't get what you wish for. You get what you work for.", author: "Unknown" },
  { text: "Fitness is not a destination. It's a way of life.", author: "Unknown" },
  { text: "Nourish your body. Nourish your soul.", author: "Unknown" },
  { text: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe" },
  { text: "Life is not measured by the number of breaths we take, but by the moments that take our breath away.", author: "Maya Angelou" },
  { text: "Today I will do what others won't, so tomorrow I can do what others can't.", author: "Jerry Rice" },
]

export function getTodayQuote() {
  const start = new Date(new Date().getFullYear(), 0, 0)
  const diff = new Date() - start
  const dayOfYear = Math.floor(diff / (1000 * 60 * 60 * 24))
  return QUOTES[dayOfYear % QUOTES.length]
}
